### ISSUE TITLE
Requests cause AttributeError

### ISSUE THREAD

**Issue by Martmists-GH** [tombulled/innertube#18]
error: 
```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/innertube/clients.py", line 87, in player
    return self(
  File "/usr/lib/python3.10/site-packages/innertube/clients.py", line 56, in __call__
    response: requests.Response = self.session.post(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/innertube/sessions.py", line 89, in send
    response: requests.Response = super().send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/innertube/sessions.py", line 48, in send
    if content_type.subtype != mediatype.MediaTypeSubtype.JSON:
AttributeError: 'dict' object has no attribute 'subtype'
```

code:
```py
>>> import innertube as it
>>> client = it.InnerTube(it.Client.ANDROID_MUSIC)
>>> client.player(video_id="ccIdf7kcH7g")
# Error
```

**Comment by tombulled** [comment]
Thank you for raising this issue, I've been able to reproduce this and will work on a PR today :slightly_smiling_face:
