### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by pixdoet** [tombulled/innertube#9]
Whenever I import innertube, it tries to import `export`, but failed to do so with the following error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/innertube/__init__.py", line 1, in <module>
    from .apis   import InnerTube
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/innertube/apis.py", line 5, in <module>
    import useragent
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/useragent/__init__.py", line 2, in <module>
    from .enums  import ProductName
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/useragent/enums.py", line 1, in <module>
    import enumb
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/enumb/__init__.py", line 1, in <module>
    from .bases      import *
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/enumb/bases.py", line 5, in <module>
    from . import generators
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/enumb/generators.py", line 6, in <module>
    from . import models
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/enumb/models.py", line 8, in <module>
    class Arguments:
TypeError: 'module' object is not callable`

This happens on python 3.8.7 on MacOS 10.14. I'm not sure about other operating systems and such.
Before this, it complained about `exports` not available, which I installed with `python3 -m pip install exports`

**Comment by tombulled** [comment]
I assume you are trying to import https://github.com/tombulled/export. This library is currently released to `pypi` under the name `expo`, however I have requested a name transfer for the `export` project name. I've got a few changes in the `dev` branch I'll work to get ready to merge which should solve this issue

**Comment by tombulled** [comment]
I've merged the `dev` branch. You should be able to easily install the library now using `pip install innertube`

**Comment by pixdoet** [comment]
It's still outputting the same error when I import innertube.

**Comment by tombulled** [comment]
I was able to reproduce your issue and have now released `v1.0.8`, does a `pip install --upgrade innertube` do the trick?

**Comment by pixdoet** [comment]
It does! Thanks for helping.
